version: '3'
services:
  javaps:
    build: .
    image: wacodis/javaps-wacodis-backend:1.1.0
    env_file:
      - ./docker/wacodis.env
    ports:
      - 8081:8080
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    environment:
      # Publicly accessible URL of the service
      SERVICE_SERVICE_URL: http://localhost:8081/wacodis-javaps/service
      SERVICE_PROVIDER_INDIVIDUAL_NAME: TBA
      SERVICE_PROVIDER_POSITION_NAME: First Line Supporter (24/7)
    volumes:
      - ./docker/config/tools:/tmp/tools
      - ./docker/config/gpf:/tmp/gpf
      - ./docker/outputs:/tmp/workdir
      - /var/run/docker.sock:/var/run/docker.sock
